name: 'PicoTool'
description: 'Run PicoTool'
inputs:
  command:
    description: 'The command to execute with picotool (info, load, safe, verify, reboot, help'
    required: 'true'
    default: 'help'
  arguments:
    decription: 'The arguments passed to the command'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.command}}
    - ${{inputs.arguments}}
